### ISSUE TITLE
sunra/php-simple-html-dom-parser is incompatible with PHP 7.3

### ISSUE THREAD

**Issue by normanlolx** [chemel/dom-parser-helper#1]
sunra/php-simple-html-dom-parser is abandoned and incompatible with PHP 7.3, see https://github.com/sunra/php-simple-html-dom-parser/issues/64.

https://github.com/Kub-AT/php-simple-html-dom-parser is suggested as PHP 7.3 compatible replacement.

**Comment by chemel** [comment]
Job done. Thank you for notifying me.
